[project]
site_name = "Django UrlConf Checks"
site_url = "https://AliSayyah.github.io/django-urlconfchecks"
repo_url = "https://github.com/AliSayyah/django-urlconfchecks"
use_directory_urls = false
nav = [
  { "Home" = "index.md" },
  { "Installation" = "installation.md" },
  { "Usage" = "usage.md" },
  { "Configuration" = "configuration.md" },
  { "Contributing" = "contributing.md" },
  { "Changelog" = "changelog.md" },
]

[project.theme]
features = [
  "content.code.copy",
  "navigation.footer",
  "navigation.top",
  "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions.pymdownx.snippets]
base_path = ["."]

[project.markdown_extensions.pymdownx.highlight]

[project.markdown_extensions.pymdownx.superfences]

[project.plugins.offline]
